import {
  Profile,
  Hotel,
  NGO,
  Volunteer,
  Listing,
  Pickup,
  Tag,
  Flag,
  ScoreSnapshot,
  NewsItem,
  PlatformSettings,
  Certificate
} from '@/types';

export const SEED_PROFILES: Profile[] = [
  {
    id: 'user-hotel-1',
    role: 'hotel',
    full_name: 'Chef Rajesh Nair',
    phone: '+91 98450 12345',
    email: 'kitchen@grandpalace.com',
    avatar_url: 'https://images.unsplash.com/photo-1577219491135-ce391730fb2c?w=150&auto=format&fit=crop&q=80',
    created_at: '2026-08-01T08:00:00Z',
  },
  {
    id: 'user-hotel-2',
    role: 'hotel',
    full_name: 'Anita Roy',
    phone: '+91 98450 23456',
    email: 'manager@spiceroutebistro.com',
    avatar_url: 'https://images.unsplash.com/photo-1583394293214-28ded15ee548?w=150&auto=format&fit=crop&q=80',
    created_at: '2026-08-10T09:30:00Z',
  },
  {
    id: 'user-hotel-3',
    role: 'hotel',
    full_name: 'Vikram Mehta',
    phone: '+91 98450 34567',
    email: 'events@royalpalms.com',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    created_at: '2026-08-15T11:00:00Z',
  },
  {
    id: 'user-hotel-4',
    role: 'hotel',
    full_name: 'Warden S. Kulkarni',
    phone: '+91 98450 45678',
    email: 'mess@greenwoodresidency.org',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    created_at: '2026-08-20T14:15:00Z',
  },
  {
    id: 'user-hotel-5',
    role: 'hotel',
    full_name: 'Samantha D’Souza',
    phone: '+91 98450 56789',
    email: 'operations@azurebayresort.com',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    created_at: '2026-09-01T10:00:00Z',
  },
  {
    id: 'user-ngo-1',
    role: 'ngo',
    full_name: 'Sister Teresa Maria',
    phone: '+91 99000 11111',
    email: 'coordinator@robinhoodkitchen.org',
    avatar_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    created_at: '2026-07-15T10:00:00Z',
  },
  {
    id: 'user-ngo-2',
    role: 'ngo',
    full_name: 'Kavita Menon',
    phone: '+91 99000 22222',
    email: 'contact@hopeshelter.org',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    created_at: '2026-07-20T12:00:00Z',
  },
  {
    id: 'user-ngo-3',
    role: 'ngo',
    full_name: 'Pastor Thomas Paul',
    phone: '+91 99000 33333',
    email: 'director@cityharvest.org',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    created_at: '2026-09-10T16:00:00Z',
  },
  {
    id: 'user-volunteer-1',
    role: 'volunteer',
    full_name: 'Arun Kumar',
    phone: '+91 97400 55555',
    email: 'arun.k@volunteer.org',
    avatar_url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    created_at: '2026-08-01T15:00:00Z',
  },
  {
    id: 'user-volunteer-2',
    role: 'volunteer',
    full_name: 'Maya Sharma',
    phone: '+91 97400 66666',
    email: 'maya.s@volunteer.org',
    avatar_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    created_at: '2026-08-05T11:20:00Z',
  },
  {
    id: 'user-public-1',
    role: 'public',
    full_name: 'Priya Patel',
    phone: '+91 98800 77777',
    email: 'priya.patel@citycitizen.in',
    avatar_url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
    created_at: '2026-08-12T10:00:00Z',
  },
  {
    id: 'user-admin-1',
    role: 'admin',
    full_name: 'Elena Vance (Platform Director)',
    phone: '+91 98111 00000',
    email: 'admin@foodrescue.org',
    avatar_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    created_at: '2026-07-01T00:00:00Z',
  }
];

export const SEED_HOTELS: Hotel[] = [
  {
    id: 'hotel-1',
    owner_id: 'user-hotel-1',
    name: 'Grand Palace Hotel & Banquets',
    slug: 'grand-palace-hotel',
    venue_type: 'hotel',
    address: '42 MG Road, Central Business District, Bengaluru',
    lat: 12.9756,
    lng: 77.6067,
    rooms: 180,
    seats: 120,
    banquet_capacity: 450,
    events_per_month: 8,
    operating_days_per_week: 7,
    status: 'approved',
    public_listing: true,
    verification_doc_path: '/docs/fssai_grand_palace.pdf',
    created_at: '2026-08-01T08:00:00Z',
  },
  {
    id: 'hotel-2',
    owner_id: 'user-hotel-2',
    name: 'The Spice Route Bistro',
    slug: 'the-spice-route-bistro',
    venue_type: 'restaurant',
    address: '14 100ft Road, Indiranagar, Bengaluru',
    lat: 12.9784,
    lng: 77.6408,
    rooms: 0,
    seats: 85,
    banquet_capacity: 0,
    events_per_month: 2,
    operating_days_per_week: 6,
    status: 'approved',
    public_listing: true,
    verification_doc_path: '/docs/fssai_spice_route.pdf',
    created_at: '2026-08-10T09:30:00Z',
  },
  {
    id: 'hotel-3',
    owner_id: 'user-hotel-3',
    name: 'Royal Palms Celebration Hall',
    slug: 'royal-palms-celebration-hall',
    venue_type: 'banquet_hall',
    address: '77 Old Airport Road, Kodihalli, Bengaluru',
    lat: 12.9592,
    lng: 77.6499,
    rooms: 0,
    seats: 0,
    banquet_capacity: 750,
    events_per_month: 16,
    operating_days_per_week: 5,
    status: 'approved',
    public_listing: true,
    verification_doc_path: '/docs/bbmp_trade_licence.pdf',
    created_at: '2026-08-15T11:00:00Z',
  },
  {
    id: 'hotel-4',
    owner_id: 'user-hotel-4',
    name: 'Greenwood Student Residency',
    slug: 'greenwood-student-residency',
    venue_type: 'hostel',
    address: '102 Hosur Main Road, Koramangala, Bengaluru',
    lat: 12.9352,
    lng: 77.6245,
    rooms: 220,
    seats: 160,
    banquet_capacity: 0,
    events_per_month: 0,
    operating_days_per_week: 7,
    status: 'approved',
    public_listing: true,
    verification_doc_path: '/docs/hostel_health_cert.pdf',
    created_at: '2026-08-20T14:15:00Z',
  },
  {
    id: 'hotel-5',
    owner_id: 'user-hotel-5',
    name: 'Azure Bay Garden Resort',
    slug: 'azure-bay-garden-resort',
    venue_type: 'hotel',
    address: '25 Outer Ring Road, Marathahalli, Bengaluru',
    lat: 12.9569,
    lng: 77.7011,
    rooms: 110,
    seats: 90,
    banquet_capacity: 300,
    events_per_month: 6,
    operating_days_per_week: 7,
    status: 'pending', // Pending admin approval
    public_listing: true,
    verification_doc_path: '/docs/fssai_pending_azure.pdf',
    created_at: '2026-09-25T10:00:00Z',
  },
];

export const SEED_NGOS: NGO[] = [
  {
    id: 'ngo-1',
    owner_id: 'user-ngo-1',
    name: 'Robin Hood Community Kitchen',
    registration_no: 'NGO-BLR-2021-9982',
    address: '5 Resthouse Crescent, Ashok Nagar, Bengaluru',
    lat: 12.9702,
    lng: 77.6094,
    capacity_portions: 600,
    service_radius_km: 15,
    trust_score: 0.98,
    status: 'approved',
    verification_doc_path: '/docs/12a_80g_robinhood.pdf',
    created_at: '2026-07-15T10:00:00Z',
  },
  {
    id: 'ngo-2',
    owner_id: 'user-ngo-2',
    name: 'Hope Shelter & Nutrition Foundation',
    registration_no: 'NGO-BLR-2019-4410',
    address: '88 5th Block, Koramangala, Bengaluru',
    lat: 12.9341,
    lng: 77.6189,
    capacity_portions: 350,
    service_radius_km: 12,
    trust_score: 0.95,
    status: 'approved',
    verification_doc_path: '/docs/trust_deed_hope.pdf',
    created_at: '2026-07-20T12:00:00Z',
  },
  {
    id: 'ngo-3',
    owner_id: 'user-ngo-3',
    name: 'City Harvest Food Bank Alliance',
    registration_no: 'NGO-BLR-2024-1188',
    address: '19 Cambridge Road, Ulsoor, Bengaluru',
    lat: 12.9789,
    lng: 77.6256,
    capacity_portions: 900,
    service_radius_km: 20,
    trust_score: 0.88,
    status: 'pending', // Pending admin approval
    verification_doc_path: '/docs/society_reg_cityharvest.pdf',
    created_at: '2026-09-28T16:00:00Z',
  },
];

export const SEED_VOLUNTEERS: Volunteer[] = [
  {
    id: 'vol-1',
    profile_id: 'user-volunteer-1',
    ngo_id: 'ngo-1',
    name: 'Arun Kumar',
    phone: '+91 97400 55555',
    vehicle: 'Electric Scooter (Insulated Cargo Crate)',
    active: true,
  },
  {
    id: 'vol-2',
    profile_id: 'user-volunteer-2',
    ngo_id: 'ngo-1',
    name: 'Maya Sharma',
    phone: '+91 97400 66666',
    vehicle: 'Electric Cargo Van (Tata Ace EV)',
    active: true,
  },
  {
    id: 'vol-3',
    profile_id: 'user-public-1',
    ngo_id: 'ngo-2',
    name: 'Priya Patel',
    phone: '+91 98800 77777',
    vehicle: 'Hatchback with Thermal Bags',
    active: true,
  },
];

export const SEED_TAGS: Tag[] = [
  { code: 'ready_on_time', label: 'Ready on Time', kind: 'positive', active: true },
  { code: 'well_packaged', label: 'Well Packaged', kind: 'positive', active: true },
  { code: 'fresh', label: 'Fresh & High Quality', kind: 'positive', active: true },
  { code: 'late', label: 'Delayed / Wait Required', kind: 'issue', active: true },
  { code: 'quantity_short', label: 'Quantity Short (< Listed)', kind: 'issue', active: true },
  { code: 'poor_packaging', label: 'Poor Packaging / Leaks', kind: 'issue', active: true },
];

export const SEED_SETTINGS: PlatformSettings = {
  score_weights: {
    rescue_rate: 0.40,
    participation: 0.20,
    listing_accuracy: 0.15,
    handoff_quality: 0.15,
    left_behind: 0.10,
  },
  smoothing_k: 5,
  min_pickups_for_board: 5,
  geofence_radius_meters: 150,
  per_ngo_weight_cap: 0.40,
  report_deadline_hours: 4,
};

// Calculate dynamic timestamps relative to right now so listings feel completely alive
const now = new Date();
const addHours = (h: number) => new Date(now.getTime() + h * 60 * 60 * 1000).toISOString();
const subHours = (h: number) => new Date(now.getTime() - h * 60 * 60 * 1000).toISOString();
const subDays = (d: number) => new Date(now.getTime() - d * 24 * 60 * 60 * 1000).toISOString();

export const SEED_LISTINGS: Listing[] = [
  {
    id: 'listing-1',
    hotel_id: 'hotel-1',
    hotel_name: 'Grand Palace Hotel & Banquets',
    hotel_address: '42 MG Road, Central Business District, Bengaluru',
    lat: 12.9756,
    lng: 77.6067,
    title: 'Executive Dinner Buffet Curry, Basmati Rice & Naan',
    description: 'Freshly prepared vegetarian paneer butter masala, yellow dal tadka, aromatic jeera rice, and sealed tandoori rotis. Kept in clean stainless food containers.',
    diet: 'veg',
    portions_listed: 45,
    cooked_at: subHours(1.5),
    pickup_by: addHours(2.5), // > 2 hours -> Green Urgency
    packaging_notes: 'Brought down to banquet loading dock B. Please bring thermal carriers.',
    safety_confirmed: true,
    status: 'posted',
    created_at: subHours(1),
  },
  {
    id: 'listing-2',
    hotel_id: 'hotel-2',
    hotel_name: 'The Spice Route Bistro',
    hotel_address: '14 100ft Road, Indiranagar, Bengaluru',
    lat: 12.9784,
    lng: 77.6408,
    title: 'Signature Kerala Roast Chicken & Parottas',
    description: 'Hot coastal chicken preparation with layered malabar parottas packed in food-grade foil containers.',
    diet: 'non_veg',
    portions_listed: 28,
    cooked_at: subHours(2),
    pickup_by: addHours(1.2), // 1-2 hours -> Amber Urgency
    packaging_notes: 'Kitchen back entrance, ask for Sous Chef Anita.',
    safety_confirmed: true,
    status: 'posted',
    created_at: subHours(1.8),
  },
  {
    id: 'listing-3',
    hotel_id: 'hotel-4',
    hotel_name: 'Greenwood Student Residency',
    hotel_address: '102 Hosur Main Road, Koramangala, Bengaluru',
    lat: 12.9352,
    lng: 77.6245,
    title: 'Breakfast Idli, Vada, Sambar & Coconut Chutney',
    description: 'Steam-hot idlis (approx 60 pcs) with crispy uddin vadas and sealed container of lentil sambar.',
    diet: 'veg',
    portions_listed: 35,
    cooked_at: subHours(2.5),
    pickup_by: addHours(0.7), // < 1 hour -> Red Urgency with pulse!
    packaging_notes: 'Dining hall counter 1. Bring large vessels.',
    safety_confirmed: true,
    status: 'posted',
    created_at: subHours(2.2),
  },
  {
    id: 'listing-4',
    hotel_id: 'hotel-3',
    hotel_name: 'Royal Palms Celebration Hall',
    hotel_address: '77 Old Airport Road, Kodihalli, Bengaluru',
    lat: 12.9592,
    lng: 77.6499,
    title: 'Banquet Wedding Feast Mixed Platters',
    description: 'Pulao, vegetable kurma, chicken biryani portions sealed in heavy-duty food foil pans.',
    diet: 'mixed',
    portions_listed: 70,
    cooked_at: subHours(2),
    pickup_by: addHours(1.8),
    packaging_notes: 'Service gate rear ramp.',
    safety_confirmed: true,
    status: 'claimed',
    created_at: subHours(1.5),
  },
  {
    id: 'listing-5',
    hotel_id: 'hotel-1',
    hotel_name: 'Grand Palace Hotel & Banquets',
    hotel_address: '42 MG Road, Central Business District, Bengaluru',
    lat: 12.9756,
    lng: 77.6067,
    title: 'Continental Pastries, Sandwiches & Quiches',
    description: 'Assorted baked croissants, cheese sandwiches, and vegetable quiches.',
    diet: 'veg',
    portions_listed: 50,
    cooked_at: subDays(1),
    pickup_by: subDays(1),
    packaging_notes: 'Clean bakery boxes.',
    safety_confirmed: true,
    status: 'completed',
    created_at: subDays(1),
  }
];

export const SEED_PICKUPS: Pickup[] = [
  {
    id: 'pickup-active-1',
    listing_id: 'listing-4',
    ngo_id: 'ngo-1',
    ngo_name: 'Robin Hood Community Kitchen',
    volunteer_id: 'vol-1',
    volunteer_name: 'Arun Kumar',
    volunteer_phone: '+91 97400 55555',
    status: 'on_the_way',
    claimed_at: subHours(0.8),
    started_at: subHours(0.3),
    voided: false,
    created_at: subHours(0.8),
    current_location: {
      lat: 12.9645,
      lng: 77.6321,
      accuracy_m: 8.5,
      updated_at: new Date().toISOString(),
    },
    eta_minutes: 7,
  },
  {
    id: 'pickup-completed-1',
    listing_id: 'listing-5',
    ngo_id: 'ngo-1',
    ngo_name: 'Robin Hood Community Kitchen',
    volunteer_id: 'vol-1',
    volunteer_name: 'Arun Kumar',
    volunteer_phone: '+91 97400 55555',
    status: 'completed',
    claimed_at: subDays(1),
    started_at: subDays(1),
    collected_at: subDays(1),
    completed_at: subDays(1),
    collected_in_geofence: true,
    portions_received: 50,
    left_behind_portions: 0,
    photo_path: 'https://images.unsplash.com/photo-1593113598332-cd288d649433?w=500&auto=format&fit=crop&q=80',
    tags: ['ready_on_time', 'well_packaged', 'fresh'],
    voided: false,
    created_at: subDays(1),
  },
  {
    id: 'pickup-flagged-1',
    listing_id: 'listing-flagged',
    ngo_id: 'ngo-2',
    ngo_name: 'Hope Shelter & Nutrition Foundation',
    volunteer_id: 'vol-3',
    volunteer_name: 'Priya Patel',
    volunteer_phone: '+91 98800 77777',
    status: 'completed',
    claimed_at: subDays(2),
    started_at: subDays(2),
    collected_at: subDays(2),
    completed_at: subDays(2),
    collected_in_geofence: false, // Geofence mismatch flag trigger!
    portions_received: 18, // Listed 45, received 18 -> Mismatch flag trigger!
    left_behind_portions: 10,
    photo_path: 'https://images.unsplash.com/photo-1541544741938-0af808871cc0?w=500&auto=format&fit=crop&q=80',
    tags: ['late', 'quantity_short'],
    voided: false,
    created_at: subDays(2),
  }
];

export const SEED_FLAGS: Flag[] = [
  {
    id: 'flag-1',
    pickup_id: 'pickup-flagged-1',
    pickup: SEED_PICKUPS[2],
    hotel_name: 'Grand Palace Hotel & Banquets',
    ngo_name: 'Hope Shelter & Nutrition Foundation',
    reason: 'Significant portions mismatch (listed 45 vs reported 18) and collection marked outside geofence (380m distance).',
    source: 'auto',
    status: 'open',
    created_at: subDays(2),
  },
];

export const SEED_SCORE_SNAPSHOTS: ScoreSnapshot[] = [
  {
    id: 'score-1',
    hotel_id: 'hotel-1',
    hotel_name: 'Grand Palace Hotel & Banquets',
    hotel_slug: 'grand-palace-hotel',
    venue_type: 'hotel',
    period_start: '2026-08-01',
    period_end: '2026-09-30',
    completed_pickups: 26,
    portions_rescued: 1420,
    rescue_rate: 0.94,
    participation: 0.88,
    listing_accuracy: 0.96,
    handoff_quality: 0.95,
    left_behind: 0.98,
    composite: 94.2,
    tier: 'forest',
    rank_in_category: 1,
    eligible: true,
    trend: 'up',
    streak_weeks: 7,
    created_at: subDays(3),
  },
  {
    id: 'score-2',
    hotel_id: 'hotel-2',
    hotel_name: 'The Spice Route Bistro',
    hotel_slug: 'the-spice-route-bistro',
    venue_type: 'restaurant',
    period_start: '2026-08-01',
    period_end: '2026-09-30',
    completed_pickups: 19,
    portions_rescued: 680,
    rescue_rate: 0.89,
    participation: 0.82,
    listing_accuracy: 0.91,
    handoff_quality: 0.90,
    left_behind: 0.95,
    composite: 88.5,
    tier: 'canopy',
    rank_in_category: 1,
    eligible: true,
    trend: 'up',
    streak_weeks: 4,
    created_at: subDays(3),
  },
  {
    id: 'score-3',
    hotel_id: 'hotel-3',
    hotel_name: 'Royal Palms Celebration Hall',
    hotel_slug: 'royal-palms-celebration-hall',
    venue_type: 'banquet_hall',
    period_start: '2026-08-01',
    period_end: '2026-09-30',
    completed_pickups: 14,
    portions_rescued: 1150,
    rescue_rate: 0.85,
    participation: 0.75,
    listing_accuracy: 0.88,
    handoff_quality: 0.86,
    left_behind: 0.90,
    composite: 85.1,
    tier: 'canopy',
    rank_in_category: 1,
    eligible: true,
    trend: 'same',
    streak_weeks: 5,
    created_at: subDays(3),
  },
  {
    id: 'score-4',
    hotel_id: 'hotel-4',
    hotel_name: 'Greenwood Student Residency',
    hotel_slug: 'greenwood-student-residency',
    venue_type: 'hostel',
    period_start: '2026-08-01',
    period_end: '2026-09-30',
    completed_pickups: 11,
    portions_rescued: 490,
    rescue_rate: 0.79,
    participation: 0.70,
    listing_accuracy: 0.84,
    handoff_quality: 0.80,
    left_behind: 0.88,
    composite: 79.4,
    tier: 'sprout',
    rank_in_category: 1,
    eligible: true,
    trend: 'up',
    streak_weeks: 3,
    created_at: subDays(3),
  },
];

export const SEED_CERTIFICATES: Certificate[] = [
  {
    id: 'cert-1',
    hotel_id: 'hotel-1',
    month: '2026-09',
    pdf_path: '/certificates/cert_grand_palace_2026_09.pdf',
    meals: 720,
    ngos_served: 2,
    co2_kg_avoided: 1800,
    created_at: '2026-10-01T00:00:00Z',
  }
];

export const SEED_NEWS: NewsItem[] = [
  {
    id: 'news-1',
    source_type: 'internal',
    title: 'Platform Milestone: Over 25,000 Surplus Meals Rescued Across Bengaluru',
    snippet: 'Together with 14 hospitality partners and 8 verified community kitchens, the FoodRescue initiative has redirected edible surplus food to over 9,000 vulnerable families this quarter.',
    source_name: 'FoodRescue Foundation',
    status: 'published',
    pinned: true,
    published_at: subDays(2),
    image_url: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=600&auto=format&fit=crop&q=80',
    created_at: subDays(2),
  },
  {
    id: 'news-2',
    source_type: 'internal',
    title: 'Behind the Scenes: How Grand Palace Hotel Reduced Kitchen Food Waste by 85%',
    snippet: 'Executive Chef Rajesh Nair shares how implementing rapid 30-second surplus dispatching transformed their banquet operations and earned them the coveted Forest Tier Rescue Score.',
    source_name: 'Impact Stories',
    status: 'published',
    pinned: false,
    published_at: subDays(4),
    image_url: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=600&auto=format&fit=crop&q=80',
    created_at: subDays(4),
  },
  {
    id: 'news-3',
    source_type: 'external',
    title: 'City Municipal Body Praises Tech Solutions Tackling Urban Food Wastage',
    snippet: 'Urban local bodies emphasize community-led distribution platforms to divert organic waste from overflowing landfills while addressing food insecurity.',
    source_name: 'The Urban Chronicle',
    url: 'https://example.com/city-food-waste-report',
    status: 'published',
    pinned: false,
    published_at: subDays(6),
    image_url: 'https://images.unsplash.com/photo-1532629345422-7515f3d16bb6?w=600&auto=format&fit=crop&q=80',
    created_at: subDays(6),
  },
];
